### ISSUE TITLE
Users.json

### ISSUE THREAD

**Issue by Emanuelbessa** [catman85/UNIPI-Smart-Degrees#1]
Hello
First i would like to thank you for making this code available, that's exactly what im looking for my academic project

I'm trying to follow your steps and everything is going ok until step 5 - **If the migration was successful, copy the file ~ / UNIPI-Smart-Degrees / build / contracts / Users.json (which contains the "abi") into the folder ~ / UNIPI-Smart-Degrees / frontend / src / assets /**

Is it possible to explain more about it?
When I go to the contracts folder, the users.json file does not appear.
Is this users.json file to appear in that folder?

Sorry for my inexperience and thank you for any help

![contracts folder](https://user-images.githubusercontent.com/41740085/65666585-57e36980-e014-11e9-9f78-f4887c726f89.png)

**Comment by Emanuelbessa** [comment]
I could better understand the situation and everything worked, my difficulty now is to interact with the contract by adding teachers and students.

sorry for the inconvenience

**Comment by catman85** [comment]
There is no Users.json file generated in build/contracts/.
It's a mistake I made in the docs. I will fix it rigth now.
**Just copy Degrees.json instead**
Thanks for mentioning!

**Comment by catman85** [comment]
Problem solved 7b06053
